dataset:
  repo_id: repo_act_test
  root: Datasets/dataset_challenge/record_pant_long_release_10/001

policy:
  type: act
  device: cuda
  push_to_hub: false

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/act_test
batch_size: 8
steps: 100
save_freq: 50
log_freq: 10

wandb:
  enable: false
